// <auto-generated />
// Arch-backed multi-world support for UnifyECS (RFC-0014).

#nullable enable

using System;
using System.Collections.Generic;
using Arch.Core;
using UnifyECS.MultiWorld;

namespace UnifyECS
{
    /// <summary>
    /// Arch-backed multi-world set. Each world is an ArchWorld, but exposed as IWorld.
    /// </summary>
    public sealed class ArchWorldSet : IWorldSet
    {
        private readonly Dictionary<string, ArchWorld> _worlds = new Dictionary<string, ArchWorld>();

        public IWorld GetOrCreate(string id)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));

            if (_worlds.TryGetValue(id, out var existing))
            {
                return existing;
            }

            var world = (ArchWorld)WorldFactory.Create(EcsBackend.Arch, new WorldConfig
            {
                Name = id
            });

            _worlds[id] = world;
            return world;
        }

        public IWorld? Get(string id)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            return _worlds.TryGetValue(id, out var world) ? (IWorld)world : null;
        }

        public IEnumerable<string> Ids => _worlds.Keys;
    }

    /// <summary>
    /// Arch-specific implementation of IMultiWorldRunner.
    /// Binds one ArchSystemRunner per world id and coordinates updates.
    /// </summary>
    public sealed class ArchMultiWorldRunner : IMultiWorldRunner
    {
        private readonly ArchWorldSet _worlds = new ArchWorldSet();
        private readonly Dictionary<string, ArchSystemRunner> _runners = new Dictionary<string, ArchSystemRunner>();
        private readonly List<IMultiWorldSystem> _multiWorldSystems = new List<IMultiWorldSystem>();
        private bool _initialized;
        private bool _disposed;

        public IWorldSet Worlds => _worlds;

        public void Register(string worldId, IUnifySystem system)
        {
            if (worldId == null) throw new ArgumentNullException(nameof(worldId));
            if (system == null) throw new ArgumentNullException(nameof(system));
            ThrowIfDisposed();

            var world = (ArchWorld)_worlds.GetOrCreate(worldId);

            if (!_runners.TryGetValue(worldId, out var runner))
            {
                runner = new ArchSystemRunner(world);
                _runners[worldId] = runner;
            }

            runner.Register(system);
        }

        public void Register(IMultiWorldSystem system)
        {
            if (system == null) throw new ArgumentNullException(nameof(system));
            ThrowIfDisposed();
            _multiWorldSystems.Add(system);
        }

        public void Initialize()
        {
            ThrowIfDisposed();

            if (_initialized)
            {
                throw new InvalidOperationException("ArchMultiWorldRunner is already initialized.");
            }

            foreach (var runner in _runners.Values)
            {
                runner.Initialize();
            }

            _initialized = true;
        }

        public void Update(float deltaTime)
        {
            ThrowIfDisposed();

            if (!_initialized)
            {
                throw new InvalidOperationException("Call Initialize() before Update().");
            }

            foreach (var runner in _runners.Values)
            {
                runner.Update(deltaTime);
            }

            foreach (var system in _multiWorldSystems)
            {
                system.Update(_worlds, deltaTime);
            }
        }

        public void Dispose()
        {
            if (_disposed)
            {
                return;
            }

            foreach (var runner in _runners.Values)
            {
                runner.Dispose();
            }

            _runners.Clear();
            _multiWorldSystems.Clear();
            _disposed = true;
        }

        private void ThrowIfDisposed()
        {
            if (_disposed)
            {
                throw new ObjectDisposedException(nameof(ArchMultiWorldRunner));
            }
        }
    }

    /// <summary>
    /// Thin adapter to wrap existing Arch.Core.World + update delegate as an IArchSystem.
    /// This allows gradual adoption of attribute-based systems in multi-world setups.
    /// </summary>
    public sealed class ArchSystemAdapter : IArchSystem
    {
        private readonly Action<World, float> _update;

        public ArchSystemAdapter(Action<World, float> update)
        {
            _update = update ?? throw new ArgumentNullException(nameof(update));
        }

        public void Execute(World world, float deltaTime)
        {
            if (world == null) throw new ArgumentNullException(nameof(world));
            _update(world, deltaTime);
        }
    }
}
