using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using UnifyECS;

namespace UnifyECS.Generators.Backends
{
    /// <summary>
    /// Common interface for backend emitters (RFC-0005).
    /// </summary>
    internal interface IBackendEmitter
    {
        EcsBackend Backend { get; }
        EcsFeature NativeFeatures { get; }
        EcsFeature EmulatableFeatures { get; }

        string EmitComponent(ComponentModel component);
        string EmitSystem(SystemModel system, FeatureSupportLevel level);
        string EmitWorldExtensions(IReadOnlyList<ComponentModel> components);
        string? EmitReactiveEmulation(SystemModel system);
        string EmitBootstrap(IReadOnlyList<SystemModel> systems);
    }

    /// <summary>
    /// Arch ECS backend emitter. Generates IArchSystem implementations that
    /// call into World.Query with QueryDescription, as described in RFC-0005.
    /// This is a first-pass skeleton focused on basic queries.
    /// </summary>
    internal sealed class ArchBackendEmitter : IBackendEmitter
    {
        public EcsBackend Backend => EcsBackend.Arch;

        public EcsFeature NativeFeatures => BackendCapabilities.GetNativeFeatures(EcsBackend.Arch);

        public EcsFeature EmulatableFeatures => BackendCapabilities.GetEmulatableFeatures(EcsBackend.Arch);

        public string EmitComponent(ComponentModel component)
        {
            // For Arch, structs can be used directly as components. We optionally
            // emit small helper extensions later; for now return an empty string.
            return string.Empty;
        }

        public string EmitSystem(SystemModel system, FeatureSupportLevel level)
        {
            if (!system.IsPartial)
                return string.Empty;

            // For now we only handle systems with at least one query.
            if (system.Queries.Length == 0)
                return string.Empty;

            var hasDeferredStructuralQueries = false;
            foreach (var query in system.Queries)
            {
                if (!query.HasStructuralChanges)
                    continue;

                if (query.StructuralChangeMode == StructuralChangeMode.Deferred ||
                    query.StructuralChangeMode == StructuralChangeMode.Auto)
                {
                    hasDeferredStructuralQueries = true;
                    break;
                }
            }

            var hasInjectedCommandBuffer = !string.IsNullOrEmpty(system.CommandBufferMemberName);
            var needsWorldAdapter = hasDeferredStructuralQueries && hasInjectedCommandBuffer;

            var hasReactiveHandlers = system.ReactiveHandlers is { Length: > 0 };
            var emitReactiveCalls = hasReactiveHandlers && level == FeatureSupportLevel.Emulated;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            if (level == FeatureSupportLevel.Emulated)
            {
                sb.AppendLine("// UnifyECS Arch backend system implementation (with emulated features)");
                sb.AppendLine("// NOTE: One or more required features are configured as Emulate for this backend.");
            }
            else
            {
                sb.AppendLine("// UnifyECS Arch backend system implementation");
            }
            sb.AppendLine("using System;");
            sb.AppendLine("using Arch.Core;");
            sb.AppendLine("using Arch.Core.Extensions;");
            sb.AppendLine("using Arch.Core.Utils;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.Append("namespace ").Append(system.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(system.Namespace) ? string.Empty : "    ";
            var accessibility = ToAccessibilityString(system.Accessibility);

            sb.Append(indent)
              .Append(accessibility)
              .Append(" partial class ")
              .Append(system.Name)
              .Append(" : global::UnifyECS.IArchSystem")
              .AppendLine();
            sb.Append(indent).AppendLine("{");

            // QueryDescription fields per query (cached queries)
            foreach (var query in system.Queries)
            {
                if (!query.Cached)
                {
                    continue;
                }

                var fieldName = "_query_" + query.MethodName;
                sb.Append(indent).Append("    private static readonly QueryDescription ")
                  .Append(fieldName)
                  .Append(" = new QueryDescription()");

                // Append filters if any; if none, this remains a match-all query.
                AppendQueryDescription(sb, query);

                // TODO: Any/None support can be added later
                sb.AppendLine(";");
            }

            sb.AppendLine();

            // InlineQuery handler structs for optimized simple queries
            if (system.ArchInlineQuery)
            {
                foreach (var query in system.Queries)
                {
                    // Only non-structural queries can use the InlineQuery optimization.
                    if (query.HasStructuralChanges)
                    {
                        continue;
                    }

                    if (!CanUseInlineQuery(system, query))
                    {
                        continue;
                    }

                    var handlerName = query.MethodName + "_InlineQueryHandler";

                    sb.Append(indent).Append("    private struct ")
                      .Append(handlerName)
                      .Append(" : IForEach<")
                      .Append(string.Join(", ", query.ParameterTypeNames))
                      .AppendLine(">");
                    sb.Append(indent).AppendLine("    {");

                    // Capture the outer system instance
                    sb.Append(indent).Append("        private readonly ")
                      .Append(system.Name)
                      .AppendLine(" _system;");

                    sb.Append(indent).Append("        public ")
                      .Append(handlerName)
                      .Append("(")
                      .Append(system.Name)
                      .AppendLine(" system)");
                    sb.Append(indent).AppendLine("        {");
                    sb.Append(indent).AppendLine("            _system = system;");
                    sb.Append(indent).AppendLine("        }");
                    sb.AppendLine();

                    // IForEach.Update implementation
                    sb.Append(indent).Append("        public void Update(");
                    var updateParams = new List<string>(query.ParameterTypeNames.Length);
                    for (var i = 0; i < query.ParameterTypeNames.Length; i++)
                    {
                        updateParams.Add("ref " + query.ParameterTypeNames[i] + " " + query.ParameterNames[i]);
                    }
                    sb.Append(string.Join(", ", updateParams)).AppendLine(")");
                    sb.Append(indent).AppendLine("        {");

                    var callArgs = new List<string>(query.ParameterNames.Length);
                    for (var i = 0; i < query.ParameterNames.Length; i++)
                    {
                        callArgs.Add("ref " + query.ParameterNames[i]);
                    }

                    sb.Append(indent).Append("            _system.")
                      .Append(query.MethodName)
                      .Append("(");
                    sb.Append(string.Join(", ", callArgs));
                    sb.AppendLine(");");

                    sb.Append(indent).AppendLine("        }");
                    sb.Append(indent).AppendLine("    }");
                    sb.AppendLine();
                }
            }

            if (needsWorldAdapter)
            {
                sb.Append(indent).AppendLine("    private sealed class WorldAdapter : global::UnifyECS.IWorld");
                sb.Append(indent).AppendLine("    {");
                sb.Append(indent).AppendLine("        private readonly global::Arch.Core.World _world;");
                sb.Append(indent).AppendLine("        private readonly System.Collections.Generic.Dictionary<global::UnifyECS.Entity, Arch.Core.Entity> _entityMap = new System.Collections.Generic.Dictionary<global::UnifyECS.Entity, Arch.Core.Entity>();");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public WorldAdapter(global::Arch.Core.World world)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            _world = world;");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public global::UnifyECS.Entity CreateEntity()");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            var archEntity = _world.Create(System.Array.Empty<ComponentType>());");
                sb.Append(indent).AppendLine("            var entity = new global::UnifyECS.Entity(archEntity.Id, archEntity.Version);");
                sb.Append(indent).AppendLine("            _entityMap[entity] = archEntity;");
                sb.Append(indent).AppendLine("            global::UnifyECS.ArchWorld.RegisterEntity(_world, entity, archEntity);");
                sb.Append(indent).AppendLine("            return entity;");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public global::UnifyECS.Entity CreateEntity(params object[] components)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            if (components is null || components.Length == 0)");
                sb.Append(indent).AppendLine("            {");
                sb.Append(indent).AppendLine("                return CreateEntity();");
                sb.Append(indent).AppendLine("            }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            var archEntity = _world.Create(System.Array.Empty<ComponentType>());");
                sb.Append(indent).AppendLine("            var entity = new global::UnifyECS.Entity(archEntity.Id, archEntity.Version);");
                sb.Append(indent).AppendLine("            _entityMap[entity] = archEntity;");
                sb.Append(indent).AppendLine("            global::UnifyECS.ArchWorld.RegisterEntity(_world, entity, archEntity);");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            for (int i = 0; i < components.Length; i++)");
                sb.Append(indent).AppendLine("            {");
                sb.Append(indent).AppendLine("                var component = components[i] ?? throw new System.ArgumentNullException(nameof(components));");
                sb.Append(indent).AppendLine("                AddComponent(entity, component);");
                sb.Append(indent).AppendLine("            }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            return entity;");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public bool Exists(global::UnifyECS.Entity entity)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            return _world.IsAlive(ToArch(entity));");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public void DestroyEntity(global::UnifyECS.Entity entity)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            _world.Destroy(ToArch(entity));");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public ref T Add<T>(global::UnifyECS.Entity entity, T component) where T : struct");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            var archEntity = ToArch(entity);");
                sb.Append(indent).AppendLine("            _world.Add(archEntity, in component);");
                sb.Append(indent).AppendLine("            return ref _world.Get<T>(archEntity);");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public ref T Add<T>(global::UnifyECS.Entity entity) where T : struct");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            var archEntity = ToArch(entity);");
                sb.Append(indent).AppendLine("            _world.Add<T>(archEntity);");
                sb.Append(indent).AppendLine("            return ref _world.Get<T>(archEntity);");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public bool Has<T>(global::UnifyECS.Entity entity) where T : struct");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            return _world.Has<T>(ToArch(entity));");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public ref T Get<T>(global::UnifyECS.Entity entity) where T : struct");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            var archEntity = ToArch(entity);");
                sb.Append(indent).AppendLine("            return ref _world.Get<T>(archEntity);");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public bool TryGet<T>(global::UnifyECS.Entity entity, out T component) where T : struct");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            if (_world.TryGet<T>(ToArch(entity), out var value))");
                sb.Append(indent).AppendLine("            {");
                sb.Append(indent).AppendLine("                component = value!;");
                sb.Append(indent).AppendLine("                return true;");
                sb.Append(indent).AppendLine("            }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            component = default;");
                sb.Append(indent).AppendLine("            return false;");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public void Remove<T>(global::UnifyECS.Entity entity) where T : struct");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            _world.Remove<T>(ToArch(entity));");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public int EntityCount => _world.Size;");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        public void Dispose()");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            // Adapter does not own the underlying world.");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        private void AddComponent(global::UnifyECS.Entity entity, object component)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            if (component is null)");
                sb.Append(indent).AppendLine("            {");
                sb.Append(indent).AppendLine("                throw new System.ArgumentNullException(nameof(component));");
                sb.Append(indent).AppendLine("            }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            var type = component.GetType();");
                sb.Append(indent).AppendLine("            if (!type.IsValueType)");
                sb.Append(indent).AppendLine("            {");
                sb.Append(indent).AppendLine("                throw new System.InvalidOperationException(\"Arch backend only supports struct components in CreateEntity(params object[]).\");");
                sb.Append(indent).AppendLine("            }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            var method = typeof(WorldAdapter).GetMethod(\"AddBoxed\", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);");
                sb.Append(indent).AppendLine("            var generic = method!.MakeGenericMethod(type);");
                sb.Append(indent).AppendLine("            generic.Invoke(this, new object[] { entity, component });");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        private void AddBoxed<T>(global::UnifyECS.Entity entity, object component) where T : struct");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            Add(entity, (T)component);");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("        private Arch.Core.Entity ToArch(global::UnifyECS.Entity entity)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            if (_entityMap.TryGetValue(entity, out var archEntity))");
                sb.Append(indent).AppendLine("            {");
                sb.Append(indent).AppendLine("                return archEntity;");
                sb.Append(indent).AppendLine("            }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            if (global::UnifyECS.ArchWorld.TryGetArchEntity(_world, entity, out archEntity))");
                sb.Append(indent).AppendLine("            {");
                sb.Append(indent).AppendLine("                return archEntity;");
                sb.Append(indent).AppendLine("            }");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            throw new System.InvalidOperationException(\"Entity does not belong to this WorldAdapter or has been destroyed.\");");
                sb.Append(indent).AppendLine("        }");
                sb.Append(indent).AppendLine("    }");
                sb.AppendLine();
            }

            // Execute method
            sb.Append(indent).AppendLine("    public void Execute(global::Arch.Core.World world, float deltaTime)");
            sb.Append(indent).AppendLine("    {");

            // Best-effort: if user has a DeltaTime injectable property, they
            // can use it. We simply assign; if it does not exist the user gets
            // a normal compile-time error and can remove it.
            sb.Append(indent).AppendLine("        // If this system defines a DeltaTime property, it can be set here.");
            sb.Append(indent).AppendLine("        // For v1 we do not emit an automatic assignment to avoid relying on");
            sb.Append(indent).AppendLine("        // an optional property that may not exist on all systems.");
            sb.AppendLine();

            if (hasDeferredStructuralQueries && hasInjectedCommandBuffer)
            {
                sb.Append(indent).Append("        var __commands = this.")
                  .Append(system.CommandBufferMemberName)
                  .AppendLine(";");
                sb.AppendLine();
            }

            foreach (var query in system.Queries)
            {
                var fieldName = "_query_" + query.MethodName;
                var localName = "query_" + query.MethodName;
                var hasFilters =
                    query.AllComponents.Length > 0 ||
                    query.AnyComponents.Length > 0 ||
                    query.NoneComponents.Length > 0 ||
                    query.ExclusiveComponents.Length > 0;

                var useInline = system.ArchInlineQuery &&
                                !query.HasStructuralChanges &&
                                CanUseInlineQuery(system, query);

                // For non-cached queries, build a local QueryDescription (with or without filters).
                if (!query.Cached)
                {
                    sb.Append(indent).Append("        var ")
                      .Append(localName)
                      .Append(" = new QueryDescription()");

                    // Append filters if any; if none, this is a match-all query.
                    AppendQueryDescription(sb, query);

                    sb.AppendLine(";");
                }

                var queryExpr = query.Cached ? fieldName : localName;

                if (useInline)
                {
                    var handlerName = query.MethodName + "_InlineQueryHandler";
                    var handlerVar = "handler_" + query.MethodName;

                    sb.Append(indent).Append("        var ")
                      .Append(handlerVar)
                      .Append(" = new ")
                      .Append(handlerName)
                      .AppendLine("(this);");

                    sb.Append(indent).Append("        world.InlineQuery<")
                      .Append(handlerName)
                      .Append(", ")
                      .Append(string.Join(", ", query.ParameterTypeNames))
                      .Append(">(in ")
                      .Append(queryExpr)
                      .Append(", ref ")
                      .Append(handlerVar)
                      .AppendLine(");");

                    sb.AppendLine();
                    continue;
                }

                sb.Append(indent).Append("        world.Query(in ")
                  .Append(queryExpr)
                  .Append(", (");

                // Lambda parameters mirror the user method signature (including ref/in/out),
                // except that Entity parameters are mapped to Arch.Core.Entity for Arch queries.
                var lambdaParams = new List<string>(query.ParameterTypeNames.Length);
                for (var i = 0; i < query.ParameterTypeNames.Length; i++)
                {
                    var refPrefix = GetRefPrefix(query.ParameterRefKinds[i]);
                    var typeName = query.ParameterTypeNames[i];

                    var isEntityParam =
                        string.Equals(typeName, "Entity", StringComparison.Ordinal) ||
                        string.Equals(typeName, "UnifyECS.Entity", StringComparison.Ordinal) ||
                        string.Equals(typeName, "global::UnifyECS.Entity", StringComparison.Ordinal) ||
                        typeName.EndsWith(".Entity", StringComparison.Ordinal);

                    if (isEntityParam)
                    {
                        lambdaParams.Add(refPrefix + "Arch.Core.Entity " + query.ParameterNames[i]);
                    }
                    else
                    {
                        lambdaParams.Add(refPrefix + typeName + " " + query.ParameterNames[i]);
                    }
                }

                sb.Append(string.Join(", ", lambdaParams)).AppendLine(") =>");
                sb.Append(indent).AppendLine("        {");

                var callArgs = new List<string>(query.ParameterNames.Length);
                for (var i = 0; i < query.ParameterNames.Length; i++)
                {
                    var refPrefix = GetRefPrefix(query.ParameterRefKinds[i]);
                    var typeName = query.ParameterTypeNames[i];

                    var isUnifyEntityParam =
                        string.Equals(typeName, "Entity", StringComparison.Ordinal) ||
                        string.Equals(typeName, "UnifyECS.Entity", StringComparison.Ordinal) ||
                        string.Equals(typeName, "global::UnifyECS.Entity", StringComparison.Ordinal);

                    if (isUnifyEntityParam && query.ParameterRefKinds[i] == RefKind.None)
                    {
                        // Map Arch.Core.Entity -> UnifyECS.Entity when calling the user method.
                        var name = query.ParameterNames[i];
                        callArgs.Add("new global::UnifyECS.Entity(" + name + ".Id, " + name + ".Version)");
                    }
                    else
                    {
                        callArgs.Add(refPrefix + query.ParameterNames[i]);
                    }
                }

                sb.Append(indent).Append("            ").Append(query.MethodName).Append("(");
                sb.Append(string.Join(", ", callArgs));
                sb.AppendLine(");");

                sb.Append(indent).AppendLine("        });");
                sb.AppendLine();
            }

            if (hasDeferredStructuralQueries && hasInjectedCommandBuffer)
            {
                sb.Append(indent).AppendLine("        if (__commands is not null && __commands.CommandCount > 0)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            var __worldAdapter = new WorldAdapter(world);");
                sb.Append(indent).AppendLine("            __commands.Playback(__worldAdapter);");
                sb.Append(indent).AppendLine("            __commands.Clear();");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
            }

            if (emitReactiveCalls)
            {
                var reactiveGroups = system.ReactiveHandlers
                    .GroupBy(h => h.ComponentTypeName);

                foreach (var group in reactiveGroups)
                {
                    var safeName = MakeSafeIdentifier(group.Key);
                    sb.Append(indent).Append("        __RunReactive_")
                      .Append(safeName)
                      .AppendLine("(world);");
                }

                sb.AppendLine();
            }

            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        public string EmitWorldExtensions(IReadOnlyList<ComponentModel> components)
        {
            // Stub for now; Arch does not strictly need world extensions.
            return string.Empty;
        }

        public string? EmitReactiveEmulation(SystemModel system)
        {
            if (system.ReactiveHandlers is null || system.ReactiveHandlers.Length == 0)
                return null;

            var groups = system.ReactiveHandlers
                .GroupBy(h => h.ComponentTypeName)
                .ToArray();

            if (groups.Length == 0)
                return null;

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// UnifyECS Arch reactive emulation (OnAdded/OnChanged/OnRemoved)");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Arch.Core;");
            sb.AppendLine("using Arch.Core.Utils;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.Append("namespace ").Append(system.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(system.Namespace) ? string.Empty : "    ";

            sb.Append(indent)
              .Append("partial class ")
              .Append(system.Name)
              .AppendLine();
            sb.Append(indent).AppendLine("{");

            foreach (var group in groups)
            {
                var componentTypeName = group.Key;
                var safeName = MakeSafeIdentifier(componentTypeName);

                var handlers = group.ToArray();
                var onAdded = handlers.Where(h => h.Kind == ReactiveKind.OnAdded).ToArray();
                var onChanged = handlers.Where(h => h.Kind == ReactiveKind.OnChanged).ToArray();
                var onRemoved = handlers.Where(h => h.Kind == ReactiveKind.OnRemoved).ToArray();

                // Snapshot dictionary for previous frame values
                sb.Append(indent).Append("    private readonly Dictionary<global::UnifyECS.Entity, ")
                  .Append(componentTypeName)
                  .Append("> __reactivePrev_")
                  .Append(safeName)
                  .Append(" = new Dictionary<global::UnifyECS.Entity, ")
                  .Append(componentTypeName)
                  .AppendLine(">();");

                // Query selecting all entities with this component
                sb.Append(indent).Append("    private static readonly QueryDescription __reactiveQuery_")
                  .Append(safeName)
                  .Append(" = new QueryDescription().WithAll<")
                  .Append(componentTypeName)
                  .AppendLine(">();");

                sb.AppendLine();

                // Helper: __RunReactive_<T>(World world)
                sb.Append(indent).Append("    private void __RunReactive_")
                  .Append(safeName)
                  .AppendLine("(World world)");
                sb.Append(indent).AppendLine("    {");

                sb.Append(indent).AppendLine("        var current = new Dictionary<global::UnifyECS.Entity, " + componentTypeName + ">();");
                sb.AppendLine();

                sb.Append(indent).AppendLine("        // Build current snapshot and fire OnAdded/OnChanged");
                sb.Append(indent).AppendLine("        world.Query(in __reactiveQuery_" + safeName + ", (Arch.Core.Entity archEntity, ref " + componentTypeName + " component) =>");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            var entity = new global::UnifyECS.Entity(archEntity.Id, archEntity.Version);");
                sb.AppendLine();

                sb.Append(indent).AppendLine("            if (__reactivePrev_" + safeName + ".TryGetValue(entity, out var prev))");
                sb.Append(indent).AppendLine("            {");
                if (onChanged.Length > 0)
                {
                    sb.Append(indent).AppendLine("                if (!EqualityComparer<" + componentTypeName + ">.Default.Equals(prev, component))");
                    sb.Append(indent).AppendLine("                {");
                    foreach (var handler in onChanged)
                    {
                        sb.Append(indent).Append("                    this.")
                          .Append(handler.MethodName)
                          .AppendLine("(entity, in component);");
                    }
                    sb.Append(indent).AppendLine("                }");
                }
                sb.Append(indent).AppendLine("            }");
                sb.Append(indent).AppendLine("            else");
                sb.Append(indent).AppendLine("            {");
                if (onAdded.Length > 0)
                {
                    foreach (var handler in onAdded)
                    {
                        sb.Append(indent).Append("                this.")
                          .Append(handler.MethodName)
                          .AppendLine("(entity, in component);");
                    }
                }
                sb.Append(indent).AppendLine("            }");
                sb.AppendLine();

                sb.Append(indent).AppendLine("            current[entity] = component;");
                sb.Append(indent).AppendLine("        });");
                sb.AppendLine();

                sb.Append(indent).AppendLine("        // Fire OnRemoved for entities that disappeared");
                sb.Append(indent).AppendLine("        foreach (var kv in __reactivePrev_" + safeName + ")");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            var entity = kv.Key;");
                sb.Append(indent).AppendLine("            var prev = kv.Value;");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            if (!current.ContainsKey(entity))");
                sb.Append(indent).AppendLine("            {");
                if (onRemoved.Length > 0)
                {
                    foreach (var handler in onRemoved)
                    {
                        sb.Append(indent).Append("                this.")
                          .Append(handler.MethodName)
                          .AppendLine("(entity, in prev);");
                    }
                }
                sb.Append(indent).AppendLine("            }");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();

                sb.Append(indent).AppendLine("        __reactivePrev_" + safeName + ".Clear();");
                sb.Append(indent).AppendLine("        foreach (var kv in current)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            __reactivePrev_" + safeName + ".Add(kv.Key, kv.Value);");
                sb.Append(indent).AppendLine("        }");
                sb.Append(indent).AppendLine("    }");
                sb.AppendLine();
            }

            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        public string EmitBootstrap(IReadOnlyList<SystemModel> systems)
        {
            if (systems is null || systems.Count == 0)
            {
                return string.Empty;
            }

            var orderedSystems = systems
                .Where(static s => s.IsPartial)
                .OrderBy(static s => (int)s.Phase)
                .ThenBy(static s => s.GroupFullName ?? string.Empty, StringComparer.Ordinal)
                .ThenBy(static s => s.Order)
                .ThenBy(static s => s.FullName, StringComparer.Ordinal)
                .ToArray();

            if (orderedSystems.Length == 0)
            {
                return string.Empty;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace UnifyECS");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedArchBootstrap");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void RegisterAll(global::UnifyECS.ArchSystemRunner runner)");
            sb.AppendLine("        {");
            sb.AppendLine("            RegisterAll(runner, services: null);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll(global::UnifyECS.ArchSystemRunner runner, global::System.IServiceProvider? services)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (runner is null) throw new global::System.ArgumentNullException(nameof(runner));");
            sb.AppendLine("            var factory = CreateDefaultFactory(services);");
            sb.AppendLine("            RegisterAll(runner, factory);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll(");
            sb.AppendLine("            global::UnifyECS.ArchSystemRunner runner,");
            sb.AppendLine("            global::System.Func<global::System.Type, global::UnifyECS.IUnifySystem> factory)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (runner is null) throw new global::System.ArgumentNullException(nameof(runner));");
            sb.AppendLine("            if (factory is null) throw new global::System.ArgumentNullException(nameof(factory));");
            sb.AppendLine();

            foreach (var system in orderedSystems)
            {
                sb.Append("            runner.Register((global::UnifyECS.IUnifySystem)factory(typeof(global::")
                  .Append(system.FullName)
                  .AppendLine("))); ");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static global::System.Func<global::System.Type, global::UnifyECS.IUnifySystem> CreateDefaultFactory(global::System.IServiceProvider? services)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (services is null)");
            sb.AppendLine("            {");
            sb.AppendLine("                return static type => (global::UnifyECS.IUnifySystem)global::System.Activator.CreateInstance(type)!;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return type => (global::UnifyECS.IUnifySystem)(services.GetService(type) ?? global::System.Activator.CreateInstance(type)!)!;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        public string EmitNoOpStub(SystemModel system)
        {
            if (!system.IsPartial)
                return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// UnifyECS Arch backend no-op stub (missing features)");
            sb.AppendLine("using System;");
            sb.AppendLine("using Arch.Core;");
            sb.AppendLine("using Arch.Core.Extensions;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.Append("namespace ").Append(system.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(system.Namespace) ? string.Empty : "    ";
            var accessibility = ToAccessibilityString(system.Accessibility);

            sb.Append(indent)
              .Append(accessibility)
              .Append(" partial class ")
              .Append(system.Name)
              .Append(" : global::UnifyECS.IArchSystem")
              .AppendLine();
            sb.Append(indent).AppendLine("{");

            sb.Append(indent).AppendLine("    public void Execute(World world, float deltaTime)");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        // No-op: required features are not available on Arch backend.");
            sb.Append(indent).AppendLine("    }");

            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string GetRefPrefix(RefKind refKind) => refKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.In => "in ",
            RefKind.Out => "out ",
            _ => string.Empty
        };

        private static bool CanUseInlineQuery(SystemModel system, QueryModel query)
        {
            // Only support void-returning methods
            if (!string.Equals(query.ReturnTypeName, "void", StringComparison.Ordinal) &&
                !string.Equals(query.ReturnTypeName, "System.Void", StringComparison.Ordinal))
            {
                return false;
            }

            if (query.ParameterTypeNames.Length == 0)
            {
                return false;
            }

            for (var i = 0; i < query.ParameterTypeNames.Length; i++)
            {
                var typeName = query.ParameterTypeNames[i];

                // For InlineQuery v1 we don't support entity parameters; those would
                // require IForEachWithEntity instead of IForEach.
                if (string.Equals(typeName, "Entity", StringComparison.Ordinal) ||
                    string.Equals(typeName, "UnifyECS.Entity", StringComparison.Ordinal) ||
                    string.Equals(typeName, "Arch.Core.Entity", StringComparison.Ordinal) ||
                    typeName.EndsWith(".Entity", StringComparison.Ordinal))
                {
                    return false;
                }

                // Require ref parameters so that they match IForEach.Update signature.
                if (query.ParameterRefKinds[i] != RefKind.Ref)
                {
                    return false;
                }

                // Avoid nullable/optional component types in v1.
                if (typeName.Contains("?", StringComparison.Ordinal) ||
                    typeName.StartsWith("System.Nullable<", StringComparison.Ordinal))
                {
                    return false;
                }
            }

            return true;
        }

        private static void AppendQueryDescription(StringBuilder sb, QueryModel query)
        {
            if (query.AllComponents.Length > 0)
            {
                sb.Append(".WithAll<")
                  .Append(string.Join(", ", query.AllComponents))
                  .Append(">()");
            }

            if (query.AnyComponents.Length > 0)
            {
                sb.Append(".WithAny<")
                  .Append(string.Join(", ", query.AnyComponents))
                  .Append(">()");
            }

            if (query.NoneComponents.Length > 0)
            {
                sb.Append(".WithNone<")
                  .Append(string.Join(", ", query.NoneComponents))
                  .Append(">()");
            }

            if (query.ExclusiveComponents.Length > 0)
            {
                sb.Append(".WithExclusive<")
                  .Append(string.Join(", ", query.ExclusiveComponents))
                  .Append(">()");
            }
        }

        private static string ToAccessibilityString(Accessibility accessibility) => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.Private => "private",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };

        private static string MakeSafeIdentifier(string fullName)
        {
            var sb = new StringBuilder(fullName.Length + 8);
            foreach (var ch in fullName)
            {
                if (char.IsLetterOrDigit(ch) || ch == '_')
                {
                    sb.Append(ch);
                }
                else
                {
                    sb.Append('_');
                }
            }

            if (sb.Length == 0)
            {
                return "_Reactive";
            }

            if (!char.IsLetter(sb[0]) && sb[0] != '_')
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }
    }
}
