using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using UnifyECS;

namespace UnifyECS.Generators.Backends
{
    /// <summary>
    /// Flecs.NET backend emitter. Generates IFlecsSystem implementations that
    /// call into Flecs Query, as described in RFC-0005.
    /// </summary>
    internal sealed class FlecsBackendEmitter : IBackendEmitter
    {
        public EcsBackend Backend => EcsBackend.Flecs;

        public EcsFeature NativeFeatures => BackendCapabilities.GetNativeFeatures(EcsBackend.Flecs);

        public EcsFeature EmulatableFeatures => BackendCapabilities.GetEmulatableFeatures(EcsBackend.Flecs);

        public string EmitComponent(ComponentModel component)
        {
            // For Flecs, structs can be used directly as components. We optionally
            // emit small helper extensions later; for now return an empty string.
            return string.Empty;
        }

        public string EmitSystem(SystemModel system, FeatureSupportLevel level)
        {
            if (!system.IsPartial)
                return string.Empty;

            // For now we only handle systems with at least one query.
            if (system.Queries.Length == 0)
                return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            if (level == FeatureSupportLevel.Emulated)
            {
                sb.AppendLine("// UnifyECS Flecs backend system implementation (with emulated features)");
                sb.AppendLine("// NOTE: One or more required features are configured as Emulate for this backend.");
            }
            else
            {
                sb.AppendLine("// UnifyECS Flecs backend system implementation");
            }
            sb.AppendLine("using System;");
            sb.AppendLine("using FlecsCore = Flecs.NET.Core;");
            sb.AppendLine("using UnifyECS;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.Append("namespace ").Append(system.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(system.Namespace) ? string.Empty : "    ";
            var accessibility = ToAccessibilityString(system.Accessibility);

            sb.Append(indent)
              .Append(accessibility)
              .Append(" partial class ")
              .Append(system.Name)
              .Append(" : global::UnifyECS.IFlecsSystem")
              .AppendLine();
            sb.Append(indent).AppendLine("{");

            // Emit query fields
            foreach (var query in system.Queries)
            {
                sb.Append(indent).AppendLine($"    private FlecsCore.Query _query_{query.MethodName};");
                sb.Append(indent).AppendLine($"    private bool _query_{query.MethodName}_initialized;");
            }
            sb.AppendLine();

            // Execute method
            sb.Append(indent).AppendLine("    public void Execute(FlecsWorld worldWrapper, float deltaTime)");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        var world = worldWrapper.World;");
            
            foreach (var query in system.Queries)
            {
                sb.Append(indent).AppendLine($"        if (!_query_{query.MethodName}_initialized)");
                sb.Append(indent).AppendLine("        {");
                
                // Build query
                sb.Append(indent).Append($"            _query_{query.MethodName} = world.QueryBuilder()");
                
                // Add All (required) components
                foreach(var type in query.AllComponents)
                {
                    sb.Append($".With<{type}>()");
                }
                
                // Add None (excluded) components
                foreach(var type in query.NoneComponents)
                {
                    sb.Append($".Without<{type}>()");
                }
                
                sb.AppendLine(".Build();");
                sb.Append(indent).AppendLine($"            _query_{query.MethodName}_initialized = true;");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();
                
                // Execute query
                sb.Append(indent).AppendLine($"        _query_{query.MethodName}.Run((FlecsCore.Iter it) =>");
                sb.Append(indent).AppendLine("        {");
                
                // Get column spans
                // We need to map parameter index to field index.
                // Flecs fields are 1-based index in the query terms.
                // The order of terms in QueryBuilder determines the index.
                // We added AllComponents first, then NoneComponents.
                // NoneComponents are not available as fields.
                // So valid fields correspond to AllComponents.
                // We need to match user method parameters to these fields.
                
                // Mapping strategy:
                // 1. Collect all types used in AllComponents.
                // 2. Map user parameters to these types to find their index.
                
                var allComponents = query.AllComponents;
                var paramToFieldMap = new Dictionary<string, int>(); // ParamName -> FieldIndex (1-based)
                
                // The field index corresponds to the order in .With<T>().
                
                for (int i = 0; i < query.ParameterTypeNames.Length; i++)
                {
                    var paramType = query.ParameterTypeNames[i];
                    var paramName = query.ParameterNames[i];
                    
                    if (IsEntityParameter(paramType)) continue;
                    
                    // Find index in AllComponents
                    int fieldIndex = -1;
                    for(int j=0; j<allComponents.Length; j++)
                    {
                        if(allComponents[j] == paramType)
                        {
                            fieldIndex = j + 1; // 1-based
                            break;
                        }
                    }
                    
                    if (fieldIndex != -1)
                    {
                        sb.Append(indent).AppendLine($"            var span_{paramName} = it.Field<{paramType}>({fieldIndex});");
                        paramToFieldMap[paramName] = fieldIndex;
                    }
                }
                
                sb.AppendLine();
                sb.Append(indent).AppendLine("            foreach (var i in it)");
                sb.Append(indent).AppendLine("            {");
                
                // Construct call arguments
                var callArgs = new List<string>();
                for (int i = 0; i < query.ParameterTypeNames.Length; i++)
                {
                    var paramType = query.ParameterTypeNames[i];
                    var paramName = query.ParameterNames[i];
                    var refKind = query.ParameterRefKinds[i];
                    
                    if (IsEntityParameter(paramType))
                    {
                        // Map entity
                        // it.Entity(i) returns Flecs Entity.
                        sb.Append(indent).AppendLine($"                var entity_{i} = it.Entity(i);");
                        callArgs.Add($"FlecsWorld.MapEntity(worldWrapper, entity_{i})");
                    }
                    else
                    {
                        // Access component from span
                        // ref span[i]
                        string prefix = refKind == RefKind.Ref ? "ref " : (refKind == RefKind.In ? "in " : "");
                        if (refKind == RefKind.Out) prefix = "out "; // Should not happen for queries usually unless created
                        
                        callArgs.Add($"{prefix}span_{paramName}[i]");
                    }
                }
                
                sb.Append(indent).AppendLine($"                {query.MethodName}({string.Join(", ", callArgs)});");
                
                sb.Append(indent).AppendLine("            }");
                sb.Append(indent).AppendLine("        });");
            }

            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private bool IsEntityParameter(string typeName)
        {
            return typeName == "UnifyECS.Entity" || 
                   typeName == "Entity" ||
                   typeName == "global::UnifyECS.Entity";
        }

        public string EmitWorldExtensions(IReadOnlyList<ComponentModel> components)
        {
            // Stub for now; Flecs does not strictly need world extensions.
            return string.Empty;
        }

        public string? EmitReactiveEmulation(SystemModel system)
        {
            // Reactive emulation not yet implemented for Flecs
            return null;
        }

        public string EmitBootstrap(IReadOnlyList<SystemModel> systems)
        {
            if (systems is null || systems.Count == 0)
            {
                return string.Empty;
            }

            var orderedSystems = systems
                .Where(static s => s.IsPartial)
                .OrderBy(static s => (int)s.Phase)
                .ThenBy(static s => s.GroupFullName ?? string.Empty, StringComparer.Ordinal)
                .ThenBy(static s => s.Order)
                .ThenBy(static s => s.FullName, StringComparer.Ordinal)
                .ToArray();

            if (orderedSystems.Length == 0)
            {
                return string.Empty;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace UnifyECS");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedFlecsBootstrap");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void RegisterAll(global::UnifyECS.FlecsSystemRunner runner)");
            sb.AppendLine("        {");
            sb.AppendLine("            RegisterAll(runner, services: null);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll(global::UnifyECS.FlecsSystemRunner runner, global::System.IServiceProvider? services)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (runner is null) throw new global::System.ArgumentNullException(nameof(runner));");
            sb.AppendLine("            var factory = CreateDefaultFactory(services);");
            sb.AppendLine("            RegisterAll(runner, factory);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll(");
            sb.AppendLine("            global::UnifyECS.FlecsSystemRunner runner,");
            sb.AppendLine("            global::System.Func<global::System.Type, global::UnifyECS.IUnifySystem> factory)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (runner is null) throw new global::System.ArgumentNullException(nameof(runner));");
            sb.AppendLine("            if (factory is null) throw new global::System.ArgumentNullException(nameof(factory));");
            sb.AppendLine();

            foreach (var system in orderedSystems)
            {
                sb.Append("            runner.Register((global::UnifyECS.IUnifySystem)factory(typeof(global::")
                  .Append(system.FullName)
                  .AppendLine("))); ");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static global::System.Func<global::System.Type, global::UnifyECS.IUnifySystem> CreateDefaultFactory(global::System.IServiceProvider? services)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (services is null)");
            sb.AppendLine("            {");
            sb.AppendLine("                return static type => (global::UnifyECS.IUnifySystem)global::System.Activator.CreateInstance(type)!;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return type => (global::UnifyECS.IUnifySystem)(services.GetService(type) ?? global::System.Activator.CreateInstance(type)!)!;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string ToAccessibilityString(Accessibility accessibility) => accessibility switch
        {
            Accessibility.Public    => "public",
            Accessibility.Internal  => "internal",
            Accessibility.Protected => "protected",
            Accessibility.Private   => "private",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };
    }
}
