using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using UnifyECS;

namespace UnifyECS.Generators.Backends
{
    /// <summary>
    /// Friflo.Engine.ECS backend emitter. Generates IFrifloSystem implementations that
    /// call into EntityStore with Friflo's query API.
    /// </summary>
    internal sealed class FrifloBackendEmitter : IBackendEmitter
    {
        public EcsBackend Backend => EcsBackend.Friflo;

        public EcsFeature NativeFeatures => BackendCapabilities.GetNativeFeatures(EcsBackend.Friflo);

        public EcsFeature EmulatableFeatures => BackendCapabilities.GetEmulatableFeatures(EcsBackend.Friflo);

        public string EmitComponent(ComponentModel component)
        {
            if (!component.IsPartial)
                return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Friflo.Engine.ECS;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(component.Namespace))
            {
                sb.Append("namespace ").Append(component.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(component.Namespace) ? string.Empty : "    ";
            var accessibility = ToAccessibilityString(component.Accessibility);

            sb.Append(indent)
              .Append(accessibility)
              .Append(" partial struct ")
              .Append(component.Name)
              .Append(" : IComponent")
              .AppendLine();
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(component.Namespace))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        public string EmitSystem(SystemModel system, FeatureSupportLevel level)
        {
            if (!system.IsPartial)
                return string.Empty;

            // For now we only handle systems with at least one query.
            if (system.Queries.Length == 0)
                return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            if (level == FeatureSupportLevel.Emulated)
            {
                sb.AppendLine("// UnifyECS Friflo backend system implementation (with emulated features)");
                sb.AppendLine("// NOTE: One or more required features are configured as Emulate for this backend.");
            }
            else
            {
                sb.AppendLine("// UnifyECS Friflo backend system implementation");
            }
            sb.AppendLine("using System;");
            sb.AppendLine("using Friflo.Engine.ECS;");
            sb.AppendLine("using UnifyECS;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.Append("namespace ").Append(system.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(system.Namespace) ? string.Empty : "    ";
            var accessibility = ToAccessibilityString(system.Accessibility);

            sb.Append(indent)
              .Append(accessibility)
              .Append(" partial class ")
              .Append(system.Name)
              .Append(" : global::UnifyECS.IFrifloSystem")
              .AppendLine();
            sb.Append(indent).AppendLine("{");

            // For each query method, emit Execute method that implements IFrifloSystem
            foreach (var query in system.Queries)
            {
                EmitQueryMethod(sb, system, query, level, indent);
            }

            // Main execute method for IFrifloSystem
            sb.AppendLine();
            sb.Append(indent).AppendLine("    void IFrifloSystem.Execute(EntityStore entities, float deltaTime)");
            sb.Append(indent).AppendLine("    {");

            // Execute each query
            for (int i = 0; i < system.Queries.Length; i++)
            {
                var query = system.Queries[i];
                sb.Append(indent).AppendLine($"        Execute_{query.MethodName}(entities, deltaTime);");
            }

            if (level == FeatureSupportLevel.Emulated && system.ReactiveHandlers is { Length: > 0 })
            {
                var reactiveGroups = system.ReactiveHandlers.GroupBy(h => h.ComponentTypeName);
                foreach (var group in reactiveGroups)
                {
                    var safeName = MakeSafeIdentifier(group.Key);
                    sb.Append(indent).Append("        __RunReactive_").Append(safeName).AppendLine("(entities);");
                }
            }

            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private void EmitQueryMethod(
            StringBuilder sb,
            SystemModel system,
            QueryModel query,
            FeatureSupportLevel supportLevel,
            string indent)
        {
            var methodParams = BuildMethodParameters(query, withTypes: true);

            sb.AppendLine();
            sb.Append(indent).Append("    private void Execute_")
              .Append(query.MethodName)
              .AppendLine("(EntityStore entities, float deltaTime)");
            sb.Append(indent).AppendLine("    {");

            // Build Friflo query
            var queryBuilder = new StringBuilder();
            queryBuilder.Append("var query = entities.Query()");

            // Add All (required) components
            if (query.AllComponents.Length > 0)
            {
                queryBuilder.Append(".WithAll<");
                queryBuilder.Append(string.Join(", ", query.AllComponents));
                queryBuilder.Append(">()");
            }

            // Add Any (optional) components
            if (query.AnyComponents.Length > 0)
            {
                queryBuilder.Append(".WithAny<");
                queryBuilder.Append(string.Join(", ", query.AnyComponents));
                queryBuilder.Append(">()");
            }

            // Add None (excluded) components
            if (query.NoneComponents.Length > 0)
            {
                queryBuilder.Append(".Without<");
                queryBuilder.Append(string.Join(", ", query.NoneComponents));
                queryBuilder.Append(">()");
            }

            queryBuilder.Append(";");
            sb.Append(indent).Append("        ").AppendLine(queryBuilder.ToString());
            sb.AppendLine();

            // Generate component array variable names for chunk-based iteration
            var componentArrayNames = BuildComponentArrayNames(query);

            // Execute query using chunk-based iteration (Friflo 1.4.0+)
            // Build the tuple deconstruction pattern: (comp1, comp2, ..., entities)
            sb.Append(indent).Append("        foreach (var (");
            if (componentArrayNames.Count > 0)
            {
                sb.Append(string.Join(", ", componentArrayNames));
                sb.Append(", ");
            }
            sb.AppendLine("entities) in query.Chunks)");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine("            for (int i = 0; i < entities.Length; i++)");
            sb.Append(indent).AppendLine("            {");

            // Call user's query method with the appropriate parameters
            var callArgs = BuildCallArguments(query, componentArrayNames);
            sb.Append(indent).Append($"                {query.MethodName}({callArgs});").AppendLine();

            sb.Append(indent).AppendLine("            }");
            sb.Append(indent).AppendLine("        }");
            sb.Append(indent).AppendLine("    }");
        }

        /// <summary>
        /// Builds unique variable names for each component array in chunk iteration.
        /// </summary>
        private List<string> BuildComponentArrayNames(QueryModel query)
        {
            var names = new List<string>();
            var seenTypes = new HashSet<string>();

            for (int i = 0; i < query.ParameterTypeNames.Length; i++)
            {
                var type = query.ParameterTypeNames[i];

                // Skip entity parameters - they're not part of the component arrays
                if (IsEntityParameter(type))
                    continue;

                // Generate a camelCase variable name from the type name
                // e.g., "PositionComponent" -> "positionComponent"
                var baseName = MakeSafeIdentifier(type);
                if (baseName.EndsWith("Component"))
                    baseName = baseName.Substring(0, baseName.Length - 9);
                if (baseName.EndsWith("Comp"))
                    baseName = baseName.Substring(0, baseName.Length - 4);

                // Ensure uniqueness
                string varName = ToCamelCase(baseName);
                string uniqueName = varName;
                int counter = 2;
                while (!seenTypes.Add(uniqueName))
                {
                    uniqueName = varName + counter;
                    counter++;
                }

                names.Add(uniqueName);
            }

            return names;
        }

        /// <summary>
        /// Converts a PascalCase identifier to camelCase.
        /// </summary>
        private string ToCamelCase(string input)
        {
            if (string.IsNullOrEmpty(input))
                return input;
            if (char.IsLower(input[0]))
                return input;
            return char.ToLowerInvariant(input[0]) + input.Substring(1);
        }

        /// <summary>
        /// Builds parameter list for generated query method.
        /// </summary>
        private string BuildMethodParameters(QueryModel query, bool withTypes)
        {
            var builder = new StringBuilder();

            for (int i = 0; i < query.ParameterTypeNames.Length; i++)
            {
                var type = query.ParameterTypeNames[i];
                var name = query.ParameterNames[i];

                // Skip Entity parameter as it's ref entity in the foreach
                if (IsEntityParameter(type))
                {
                    continue;
                }

                if (i > 0)
                {
                    builder.Append(", ");
                }

                if (withTypes)
                {
                    builder.Append(type);
                    builder.Append(" ");
                }

                builder.Append(name);
            }

            return builder.ToString();
        }

        /// <summary>
        /// Builds argument list for calling the user's query method.
        /// </summary>
        private string BuildCallArguments(QueryModel query, List<string>? componentArrayNames = null)
        {
            var builder = new StringBuilder();
            var argIndex = 0;
            var componentArrayIndex = 0;

            for (int i = 0; i < query.ParameterTypeNames.Length; i++)
            {
                var type = query.ParameterTypeNames[i];
                var refKind = query.ParameterRefKinds[i];
                var name = query.ParameterNames[i];

                if (IsEntityParameter(type))
                {
                    // Entity parameter from the inner for loop
                    if (argIndex > 0)
                    {
                        builder.Append(", ");
                    }

                    // Convert Friflo entity to UnifyECS entity using entities[i]
                    builder.Append($"FrifloWorld.MapEntity(entities[i])");

                    argIndex++;
                }
                else
                {
                    // Component parameters - get them from the component arrays
                    if (argIndex > 0)
                    {
                        builder.Append(", ");
                    }

                    // Get the component array variable name
                    string compVarName = componentArrayNames?[componentArrayIndex] ?? $"comp{componentArrayIndex}";

                    if (refKind == RefKind.Ref)
                    {
                        builder.Append($"ref {compVarName}[i]");
                    }
                    else if (refKind == RefKind.In)
                    {
                        builder.Append($"in {compVarName}[i]");
                    }
                    else if (refKind == RefKind.Out)
                    {
                        builder.Append($"out {compVarName}[i]");
                    }
                    else
                    {
                        builder.Append($"{compVarName}[i]");
                    }

                    argIndex++;
                    componentArrayIndex++;
                }
            }

            return builder.ToString();
        }

        /// <summary>
        /// Checks if a parameter type represents an entity (not a component).
        /// </summary>
        private bool IsEntityParameter(string typeName)
        {
            return typeName == "UnifyECS.Entity" ||
                   typeName == "Entity" ||
                   typeName == "global::UnifyECS.Entity";
        }

        public string EmitWorldExtensions(IReadOnlyList<ComponentModel> components)
        {
            // Stub for now; Friflo does not strictly need world extensions.
            return string.Empty;
        }

        public string? EmitReactiveEmulation(SystemModel system)
        {
            if (system.ReactiveHandlers is null || system.ReactiveHandlers.Length == 0)
                return null;

            var groups = system.ReactiveHandlers
                .GroupBy(h => h.ComponentTypeName)
                .ToArray();

            if (groups.Length == 0)
                return null;

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// UnifyECS Friflo reactive emulation (OnAdded/OnChanged/OnRemoved)");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Friflo.Engine.ECS;");
            sb.AppendLine("using UnifyECS;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.Append("namespace ").Append(system.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(system.Namespace) ? string.Empty : "    ";

            sb.Append(indent)
              .Append("partial class ")
              .Append(system.Name)
              .AppendLine();
            sb.Append(indent).AppendLine("{");

            foreach (var group in groups)
            {
                var componentTypeName = group.Key;
                var safeName = MakeSafeIdentifier(componentTypeName);

                var handlers = group.ToArray();
                var onAdded = handlers.Where(h => h.Kind == ReactiveKind.OnAdded).ToArray();
                var onChanged = handlers.Where(h => h.Kind == ReactiveKind.OnChanged).ToArray();
                var onRemoved = handlers.Where(h => h.Kind == ReactiveKind.OnRemoved).ToArray();

                // Snapshot dictionary for previous frame values
                sb.Append(indent).Append("    private readonly Dictionary<global::UnifyECS.Entity, ")
                  .Append(componentTypeName)
                  .Append("> __reactivePrev_")
                  .Append(safeName)
                  .Append(" = new Dictionary<global::UnifyECS.Entity, ")
                  .Append(componentTypeName)
                  .AppendLine(">();");

                // Helper: __RunReactive_<T>(EntityStore entities)
                sb.Append(indent).Append("    private void __RunReactive_")
                  .Append(safeName)
                  .AppendLine("(EntityStore entities)");
                sb.Append(indent).AppendLine("    {");

                sb.Append(indent).AppendLine("        var current = new Dictionary<global::UnifyECS.Entity, " + componentTypeName + ">();");
                sb.AppendLine();

                sb.Append(indent).AppendLine("        // Build current snapshot and fire OnAdded/OnChanged");
                sb.Append(indent).AppendLine("        var query = entities.Query().WithAll<" + componentTypeName + ">();");
                sb.Append(indent).AppendLine("        foreach (var (componentSpan, entitySpan) in query.Chunks)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            for (int i = 0; i < entitySpan.Length; i++)");
                sb.Append(indent).AppendLine("            {");
                sb.Append(indent).AppendLine("                var unifyEntity = FrifloWorld.MapEntity(entitySpan[i]);");
                sb.Append(indent).AppendLine("                var component = componentSpan[i];");
                sb.AppendLine();

                sb.Append(indent).AppendLine("            if (__reactivePrev_" + safeName + ".TryGetValue(unifyEntity, out var prev))");
                sb.Append(indent).AppendLine("            {");
                if (onChanged.Length > 0)
                {
                    sb.Append(indent).AppendLine("                if (!EqualityComparer<" + componentTypeName + ">.Default.Equals(prev, component))");
                    sb.Append(indent).AppendLine("                {");
                    foreach (var handler in onChanged)
                    {
                        sb.Append(indent).Append("                    this.")
                          .Append(handler.MethodName)
                          .AppendLine("(unifyEntity, in component);");
                    }
                    sb.Append(indent).AppendLine("                }");
                }
                sb.Append(indent).AppendLine("            }");
                sb.Append(indent).AppendLine("            else");
                sb.Append(indent).AppendLine("            {");
                if (onAdded.Length > 0)
                {
                    foreach (var handler in onAdded)
                    {
                        sb.Append(indent).Append("                this.")
                          .Append(handler.MethodName)
                          .AppendLine("(unifyEntity, in component);");
                    }
                }
                sb.Append(indent).AppendLine("            }");
                sb.AppendLine();

                sb.Append(indent).AppendLine("            current[unifyEntity] = component;");
                sb.Append(indent).AppendLine("            }");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();

                sb.Append(indent).AppendLine("        // Fire OnRemoved for entities that disappeared");
                sb.Append(indent).AppendLine("        foreach (var kv in __reactivePrev_" + safeName + ")");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            var entity = kv.Key;");
                sb.Append(indent).AppendLine("            var prev = kv.Value;");
                sb.AppendLine();
                sb.Append(indent).AppendLine("            if (!current.ContainsKey(entity))");
                sb.Append(indent).AppendLine("            {");
                if (onRemoved.Length > 0)
                {
                    foreach (var handler in onRemoved)
                    {
                        sb.Append(indent).Append("                this.")
                          .Append(handler.MethodName)
                          .AppendLine("(entity, in prev);");
                    }
                }
                sb.Append(indent).AppendLine("            }");
                sb.Append(indent).AppendLine("        }");
                sb.AppendLine();

                sb.Append(indent).AppendLine("        __reactivePrev_" + safeName + ".Clear();");
                sb.Append(indent).AppendLine("        foreach (var kv in current)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            __reactivePrev_" + safeName + ".Add(kv.Key, kv.Value);");
                sb.Append(indent).AppendLine("        }");
                sb.Append(indent).AppendLine("    }");
                sb.AppendLine();
            }

            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        public string EmitBootstrap(IReadOnlyList<SystemModel> systems)
        {
            if (systems is null || systems.Count == 0)
            {
                return string.Empty;
            }

            var orderedSystems = systems
                .Where(static s => s.IsPartial)
                .OrderBy(static s => (int)s.Phase)
                .ThenBy(static s => s.GroupFullName ?? string.Empty, StringComparer.Ordinal)
                .ThenBy(static s => s.Order)
                .ThenBy(static s => s.FullName, StringComparer.Ordinal)
                .ToArray();

            if (orderedSystems.Length == 0)
            {
                return string.Empty;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace UnifyECS");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedFrifloBootstrap");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void RegisterAll(global::UnifyECS.FrifloSystemRunner runner)");
            sb.AppendLine("        {");
            sb.AppendLine("            RegisterAll(runner, services: null);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll(global::UnifyECS.FrifloSystemRunner runner, global::System.IServiceProvider? services)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (runner is null) throw new global::System.ArgumentNullException(nameof(runner));");
            sb.AppendLine("            var factory = CreateDefaultFactory(services);");
            sb.AppendLine("            RegisterAll(runner, factory);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll(");
            sb.AppendLine("            global::UnifyECS.FrifloSystemRunner runner,");
            sb.AppendLine("            global::System.Func<global::System.Type, global::UnifyECS.IUnifySystem> factory)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (runner is null) throw new global::System.ArgumentNullException(nameof(runner));");
            sb.AppendLine("            if (factory is null) throw new global::System.ArgumentNullException(nameof(factory));");
            sb.AppendLine();

            foreach (var system in orderedSystems)
            {
                sb.Append("            runner.Register((global::UnifyECS.IUnifySystem)factory(typeof(global::")
                  .Append(system.FullName)
                  .AppendLine("))); ");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static global::System.Func<global::System.Type, global::UnifyECS.IUnifySystem> CreateDefaultFactory(global::System.IServiceProvider? services)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (services is null)");
            sb.AppendLine("            {");
            sb.AppendLine("                return static type => (global::UnifyECS.IUnifySystem)global::System.Activator.CreateInstance(type)!;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return type => (global::UnifyECS.IUnifySystem)(services.GetService(type) ?? global::System.Activator.CreateInstance(type)!)!;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        public string EmitNoOpStub(SystemModel system)
        {
            if (!system.IsPartial)
                return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// UnifyECS Friflo backend no-op stub (missing features)");
            sb.AppendLine("using System;");
            sb.AppendLine("using Friflo.Engine.ECS;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.Append("namespace ").Append(system.Namespace).AppendLine();
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(system.Namespace) ? string.Empty : "    ";
            var accessibility = ToAccessibilityString(system.Accessibility);

            sb.Append(indent)
              .Append(accessibility)
              .Append(" partial class ")
              .Append(system.Name)
              .Append(" : global::UnifyECS.IFrifloSystem")
              .AppendLine();
            sb.Append(indent).AppendLine("{");

            sb.Append(indent).AppendLine("    public void Execute(EntityStore entities, float deltaTime)");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        // No-op: required features are not available on Friflo backend.");
            sb.Append(indent).AppendLine("    }");

            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(system.Namespace))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string ToAccessibilityString(Accessibility accessibility) => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.Private => "private",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };

        private static string MakeSafeIdentifier(string fullName)
        {
            var sb = new StringBuilder(fullName.Length + 8);
            foreach (var ch in fullName)
            {
                if (char.IsLetterOrDigit(ch) || ch == '_')
                {
                    sb.Append(ch);
                }
                else
                {
                    sb.Append('_');
                }
            }

            if (sb.Length == 0)
            {
                return "_Reactive";
            }

            if (!char.IsLetter(sb[0]) && sb[0] != '_')
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }
    }
}
