// <auto-generated />
// Core multi-world abstractions for UnifyECS (RFC-0014).

#nullable enable

using System;
using System.Collections.Generic;

namespace UnifyECS.MultiWorld
{
    /// <summary>
    /// Represents a set of named worlds managed together.
    /// Implementations may be backend-specific but expose IWorld handles.
    /// </summary>
    public interface IWorldSet
    {
        IWorld GetOrCreate(string id);
        IWorld? Get(string id);
        IEnumerable<string> Ids { get; }
    }

    /// <summary>
    /// A system that operates across multiple worlds.
    /// Typically used for cross-world coordination or diagnostics.
    /// </summary>
    public interface IMultiWorldSystem
    {
        void Update(IWorldSet worlds, float deltaTime);
    }

    /// <summary>
    /// Orchestrates systems for multiple worlds.
    /// Wraps one or more single-world runners and provides a multi-world view.
    /// </summary>
    public interface IMultiWorldRunner : IDisposable
    {
        IWorldSet Worlds { get; }

        /// <summary>
        /// Register a system that operates on a specific world.
        /// </summary>
        void Register(string worldId, IUnifySystem system);

        /// <summary>
        /// Register a system that can see all worlds.
        /// </summary>
        void Register(IMultiWorldSystem system);

        /// <summary>
        /// Perform initialization (e.g., dependency injection) for all worlds.
        /// </summary>
        void Initialize();

        /// <summary>
        /// Update all worlds and systems for a single frame.
        /// </summary>
        void Update(float deltaTime);
    }
}
